# Generated by Django 4.0.2 on 2022-04-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_course_abc_to_mti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
